#ifndef __DEFINES_H
# define __DEFINES_H

#define BLOCK_SIZE 32
#define BLOCKS_PER_SIDE 30
#define WIDTH_HEIGTH (BLOCK_SIZE * BLOCKS_PER_SIDE)
#define ARRAY_SIZE (WIDTH_HEIGTH * WIDTH_HEIGTH * 4)
#define BLOCK_PIXELS_SIZE (BLOCK_SIZE * BLOCK_SIZE * 4)
#define OBSTACLES_QUANTITY 4//TODO: tmp
#define TARGETS_QUANTITY 4//TODO: tmp

#endif