#ifndef __DEFINES_H
# define __DEFINES_H

#define WIDTH_HEIGTH 960
#define ARRAY_SIZE WIDTH_HEIGTH * WIDTH_HEIGTH * 4
#define BLOCK_SIZE 32
#define BLOCKS_QUANTITY WIDTH_HEIGTH / BLOCK_SIZE * WIDTH_HEIGTH / BLOCK_SIZE
#define BLOCK_PIXELS_SIZE BLOCK_SIZE * BLOCK_SIZE * 4
#define OBSTACLES_QUANTITY 4//TODO: tmp
#define TARGETS_QUANTITY 4//TODO: tmp

#endif