#ifndef __DEFINES_H
# define __DEFINES_H

#define BLOCK_SIZE 48
#define BLOCK_PIXELS_SIZE (BLOCK_SIZE * BLOCK_SIZE * 4)
#define OBSTACLES_QUANTITY 4//TODO: tmp
#define TARGETS_QUANTITY 4//TODO: tmp

#endif